# Generated by Django 3.1.4 on 2020-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201202_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
