# Generated by Django 3.1.4 on 2020-12-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201202_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='pub_date',
        ),
    ]
