# Generated by Django 3.1.4 on 2020-12-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUsers',
            new_name='AppUser',
        ),
    ]
