# Generated by Django 3.1.4 on 2020-12-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201204_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='email',
        ),
    ]
