# Generated by Django 3.1.4 on 2020-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_type_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('instructors', models.ManyToManyField(related_name='instrictors', to='core.user_type')),
                ('students', models.ManyToManyField(related_name='students', to='core.user_type')),
                ('tas', models.ManyToManyField(related_name='Tas', to='core.user_type')),
            ],
        ),
    ]
