# Generated by Django 3.1.4 on 2020-12-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20201204_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='Sentby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sennder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
