# Generated by Django 3.1.4 on 2020-12-05 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20201205_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ReadBy',
            field=models.ManyToManyField(default=[1], related_name='readby', to=settings.AUTH_USER_MODEL),
        ),
    ]
