# Generated by Django 3.1.4 on 2020-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201205_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
