# Generated by Django 3.1.4 on 2020-12-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('OTP', models.CharField(max_length=6)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
